### ISSUE TITLE
Line breaks in code blocks not preserved

### ISSUE THREAD

**Issue by dmytrokyrychuk** [mipmip/home-manager-option-search#26]
The example value for the `xfconf.settings` option is a multiline string: https://github.com/nix-community/home-manager/blob/6b28ab2d798c1c84e24053d95f4ee1dd9d81e2fb/modules/misc/xfconf.nix#L84-L95
This example is rendered correctly in HM documentation: https://nix-community.github.io/home-manager/options.xhtml#opt-xfconf.settings
But the same example in the option search web page is rendered on one line:  
![image](https://github.com/mipmip/home-manager-option-search/assets/699961/0aadf76b-e6c3-45eb-89b6-d3f704b1323d)

**Comment by arminius-smh** [comment]
I thought that to be annoying as well, I 'fixed' it here in my fork: https://github.com/arminius-smh/home-manager-option-search/commit/d3569796b6a37bb0d58cff1af83e49468c298363

![codeformat](https://github.com/mipmip/home-manager-option-search/assets/159054879/7d5f58a7-3c17-43bd-9e60-537e66a19c97)

However I don't know if this solution is really the best way to do it, I used selenium to load the js of the home manager docs and then it inserts the exact example code.

I guess https://github.com/mipmip/home-manager-option-search/issues/20 would be needed to solve that otherwise, if that solution is okay for now though @mipmip I can make a pull request.

See deployed here: https://arminius-smh.github.io/home-manager-option-search?query=

**Comment by mipmip** [comment]
this has been fixed.
